[project]
name = "music-recommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "implicit>=0.7.2",
    "pandas>=2.2.3",
    "scipy>=1.14.1",
    "typer>=0.12.5",
]
